spring:
  config:
    import: application-local-secret.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/bakkuyoung
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

file:
  upload-dir: ./uploads/

server:
  base-url: http://localhost:8080