spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  web:
    resources:
      static-locations: file:/home/ubuntu/uploads/
  mvc:
    static-path-pattern: "/uploads/**"

file:
  upload-dir: /home/ubuntu/uploads/

server:
  base-url: http://ec2-3-38-13-139.ap-northeast-2.compute.amazonaws.com:8080

jwt:
  secret: ${JWT_SECRET}